# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 13:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('main_window', 'Main_window'), ('meet_the_team', 'Meet_the_team'), ('regular_class', 'Regular_class'), ('classes', 'Classes'), ('camp', 'Camp'), ('best_picks', 'Best_picks'), ('news_events', 'News_events')], default='classes', max_length=20)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('title_ko', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='Slug')),
                ('slug_en', models.SlugField(max_length=250, null=True, unique_for_date='publish', verbose_name='Slug')),
                ('slug_ko', models.SlugField(max_length=250, null=True, unique_for_date='publish', verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='thumbnail/%Y/%m/%d')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Body')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body')),
                ('body_ko', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posting_system.Post'),
        ),
    ]
