# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0002_auto_20171015_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='thumbnail/%Y/%m/%d', verbose_name='Thumbnail Image'),
        ),
    ]
