# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0003_auto_20171015_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('main_window', 'Main_window'), ('meet_the_team', 'Meet_the_team'), ('fulltime_course', 'Fulltime_course'), ('parttime_course', 'Parttime_course'), ('camp', 'Camp'), ('best_picks', 'Best_picks'), ('news_events', 'News_events')], default='classes', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
