# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0004_auto_20171016_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('main_window', 'Main window'), ('meet_the_team', 'Meet the_team'), ('fulltime_course', 'Fulltime course'), ('parttime_course', 'Parttime course'), ('camp', 'Camp'), ('best_picks', 'Best picks'), ('news_events', 'News events')], default='classes', max_length=20, verbose_name='Category'),
        ),
    ]
