# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0004_auto_20171003_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='thumnail/%Y/%m/%d'),
        ),
    ]
