# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0004_auto_20171013_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title_t', models.CharField(db_index=True, max_length=200)),
                ('slug_t', models.SlugField(max_length=200, unique_for_date='publish')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='posting_system.Post')),
            ],
            options={
                'verbose_name': 'post Translation',
                'db_table': 'posting_system_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
