# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0004_auto_20171013_1151'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
