# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0005_auto_20171013_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ko',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ko',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
    ]
