# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 13:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0006_auto_20171013_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ko',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
