# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 14:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posting_system', '0007_auto_20171014_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_ko',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_ko',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish', verbose_name='Slug'),
        ),
    ]
